config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  root to: "users#index"
  resources :recipes

  get '/ingredients/all', to: "ingredients#get_all_and_return_json"
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, :through => :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, :through => :recipe_ingredients

  belongs_to :user
  has_one :style

  def self.styles
    Style.all
  end

  def self.search(search)
    where("name LIKE ? ", "%#{search}%") 
  end

  def style
    Style.find(self.style_id) if self.style_id
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe_ingredients.rb
class RecipeIngredients < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	def get_all_and_return_json
  	  @ingredients = Ingredient.where("user_id IS ? or user_id=?", nil, current_user.id)

  	  respond_to do |format|
        format.json {
        	render json: {:ingredients => @ingredients}
        }
  	  end
	end
end

app/controllers/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  belongs_to :user
  has_one :style

  def self.search(search)
      where("name LIKE ? " , "%#{search}%")
  end
end

app/controllers/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipes
  belongs_to :ingredients
end

app/controllers/models/style.rb
class Style < ApplicationRecord
end

app/controllers/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  if params[:search]
    @recipes = Recipe.search(params[:search]).order("created_at DESC")
  else
    @recipes = Recipe.all.order("created_at DESC")
  end
end

  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = @recipe.recipe_ingredients
  end

  def new
    recipe_form = RecipeForm.new
    styles = Recipe.styles

    render locals: { recipe_form: recipe_form, styles: styles }
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path
  end

  def create
    recipe_form = RecipeForm.new(recipe_params)
    recipe = CreateRecipe.new(user: current_user, form: recipe_form).call
    AddIngredientsToRecipe.new(recipe: recipe, form: recipe_form, current_user: current_user).call
    redirect_to recipes_path
  end

  def edit
    @recipe = Recipe.find(params[:id])
    recipe_form = RecipeForm.new
    styles = Recipe.styles

    render locals: { recipe_form: recipe_form, styles: styles }
  end

  def update
    recipe = Recipe.find(params[:id])
    recipe_form = RecipeForm.new(recipe_params, recipe)
    UpdateRecipe.new(recipe: recipe, form: recipe_form).call
    redirect_to recipes_path
  end

  private

  def recipe_params
	  params.require(:recipe_form).permit(:name, :description, :process_desc, :style_id, {:ingredients => []}, {:ingredients_custom => []}, {:ingredients_quantity => []})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Browary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <div class="container">
      <%= yield %>
      <%= form_tag(recipes_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Recipes" %>
        <%= submit_tag "Search", :name => nil %>
      <% end %>
    </div>
  </body>
</html>

app/views/recipes/edit.erb
<h1>Edit <%= @recipe.name %></h1>
<%= form_for recipe_form, url: recipe_path(@recipe), method: :put do |f| %>
	<p><%= f.text_field :name, value: @recipe.name %></p>
	<p><%= f.text_area :description, value: @recipe.description, cols: 33 %></p>
	<p><%= f.text_area :process_desc, value: @recipe.process_desc, cols: 33 %></p>
	<p>Style: <%= select_tag "recipe_form[style_id]", options_from_collection_for_select(styles, :id, :name) %></p>
	<%= f.submit "Update Recipe", class: "btn btn-primary btn-sm" %>
<% end %>

app/views/recipes/index.erb
<h1>Recipies</h1>
  <% if user_signed_in? %>
    <span><%= link_to "Add new", new_recipe_path %></span>
  <% end %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Style</th>
      <th scope="col">Process</th>
      <th scope="col">Details</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <th><%= recipe.name %></th>
        <th><%= recipe.description %></th>
        <th><%= recipe.process_desc %></th>
        <th><%= recipe.style.name %></th>
        <th><%= link_to ">>>", recipe_path(recipe) %></th>
        <th><%= link_to 'Delete', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' } %></th>
      </tr>
    <% end %>
  </tbody>
</table>
<% if @recipes.blank? %>
  <h4>There are no recipes containing the term <%= params[:search] %>.</h4>
<% end %>

app/views/recipes/new.erb
<h1>Add Recipe</h1>
<%= form_for recipe_form, url: recipes_path do |f| %>
	<p><%= f.text_field :name, placeholder: "Name" %></p>
	<p><%= f.text_area :description, placeholder: "Description", cols: 33 %></p>
	<p><%= f.text_area :process_desc, placeholder: "Process description", cols: 33 %></p>
	<p>Style: <%= select_tag "recipe_form[style_id]", options_from_collection_for_select(styles, :id, :name) %></p>
	<div class="ingredients_wrap">
		<input type="button" class="add_ingredient_button" value="Add ingredient"><br />
	</div>
	<%= f.submit "Create Recipe", class: "btn btn-primary btn-sm" %>
<% end %>

app/views/recipes/show.erb
<h1><%= @recipe.name %></h1>
<p>
  <%= @recipe.style.name %>
  <% if user_signed_in? %>
    <%= link_to "Edit", edit_recipe_path(@recipe) %>
  <% end %>
</p>
<h2>Ingredients</h2>
<table>
	<thead>
		<th>Nazwa</th>
		<th>Ilość</th>
	</thead>
	<tbody>
		<% @ingredients.each do |i| %>
			<tr>
				<td><%= i.ingredient.name %></td>
				<td><%= i.quantity %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<h2>Description</h2>
<p><%= @recipe.description %>
<h2>Process description</h2>
<p><%= @recipe.process_desc %></p>

app/views/shared/_nav.erb
<nav class="navbar navbar-inverse">
<div class="container-fluid">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Browary</a>
  </div>
  <% if user_signed_in? %>
    <ul class="nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Recipies", recipes_path %></li>
      <li><%= link_to "Ingredients", "#" %></li>
    </ul>
  <% end %>
  <ul class="nav navbar-right">
    <% if user_signed_in? %>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
    <% end %>
  </ul>
</div>
</nav>

app/views/users/index.erb
Users index

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>